//Values below are just for initialising and will be changed when synth is initialised to current panel controls & EEPROM settings
byte midiChannel = MIDI_CHANNEL_OMNI;//(EEPROM)
String patchName = INITPATCHNAME;
boolean encCW = true;//This is to set the encoder to increment when turned CW - Settings Option
float oscWaveform = 0;
String Wavestr = "          "; //for Display
int octave1 = 0;
int unison = 0;
int octaveModSW =0;
float filterRes = 0;
float filterResstr = 0;
float waveMonoMulti = 0;
float osc1Detune = 0;
float osc1Detunestr = 0;
int pitchBendRange = 8;
int PitchBendLevel = 0;
int PitchBendLevelstr = 0; // for display
float modWheelDepth = 0.2f;
float keytrackingAmount = 0.5;//MIDI CC & settings option (EEPROM)
float glideSpeedstr = 0; // for display
float glideSpeed = 0;
float glideAmountstr = 0; // for display
float glideAmount = 0;
float glideMonoMulti = 0;
float glideDest = 0;
int returnvalue = 0;
float ADSRInvert = 0;
float ADSRInvertstr = 0;
float LfoDelay = 1;
float LfoDelaystr = 0; // for display
String StratusLFOWaveform = "                ";
String StratusSUBWaveform = "                ";
String StratusOSCWaveform = "                    ";
String StratusADSRMode = "                ";
String LfoMultiplierstr = "    ";
float LfoSlope = 0;
float LfoSlopestr = 0;
float filterCutoff = 12000;
float filterCutoffstr = 12000; // for display
float filterEnv = 0; // not required
float LfoDepth = 0;
float LfoDepthstr = 0; // for display
int octave2 = 0;
int sync = 0;
int PatchA = 0;
int PatchB = 0;
int PatchC = 0;
float LfoRate = 0;
float LfoRatestr = 0; //for display
float ampAttack = 0;
float ampAttackstr = 0;
float ampDecay = 0;
float ampDecaystr = 0;
float ampSustain = 0;
float ampSustainstr = 0; // for display
float ampRelease = 0;
float ampReleasestr = 0;
float displaystr = 0;
float LFOWaveform = 0;
int LFOWaveformstr = 0;
float LfoDest = 0;
float LfoMonoMulti = 0;
float altWave = 0;
float buttonA = 0;
float buttonB = 0;
float buttonC = 0;
float sawtooth = 0;
float squarewave = 0;
float LfoVCO = 0;
float LfoVCF = 0;
float LfoVCA = 0;
float glideA = 0;
float glideB = 0;
float glideC = 0;
float glideD = 0;
float organ16 = 0;
float organ8 = 0;
float organ4 = 0;
float organ2 = 0;
float synthVolume = 0;
float organVolume = 0;
float stringsVolume = 0;
float timbre = 0;
float footages = 0;
float foot16 = 0;
float foot16str = 0;
float foot8 = 0;
float foot8str = 0;
float stringAttack = 0;
float stringRelease = 0;

// effects

int effectNumber = 0;
int pot1 = 0;
int pot1str = 0;
int pot2 = 0;
int pot2str = 0;
int pot3 = 0;
int slowpot3 = 0;
int fastpot3 = 1023;
int pot3str = 0;
int mix = 0;
int mixa = 0;
int mixb = 0;
int mixastr = 0;
int mixbstr = 0;
int internal = 0;
boolean effect = false;
int synthInput = 0;
int stringsInput = 0;
int organInput = 0;
boolean footPedal = false;
boolean fast = false;
boolean slow = false;
String FV1effect = "                ";